version: "3"

services:
  python-visualizer-api:
    image: python-visualizer-api
    container_name: python-visualizer-api
    command: python main.py
    networks:
      - no-internet
    restart: unless-stopped

  python-visualizer-api-proxy:
    image: nginx:1.21.1-alpine
    container_name: python-visualizer-api-proxy
    ports:
      - "16222:16222"
    networks:
      - internet
      - no-internet
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - python-visualizer-api
    restart: unless-stopped

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge